### ISSUE TITLE
Simulator test multiple modules 

### ISSUE THREAD

**Issue by kxtchen** [ThrowTheSwitch/CeedlingExample_Microchip#1]
This is 7 years old topic, but it is new to me. Recently I got ceedling test running with Microchip simulator MDB by following this example. Thanks to the writer although it is a bit later. But then I found a problem.

To test every single module, the simulator needs an instruction file. The only different inside is the output filename.  
For example:  

instruction_module1.txt
>Device PIC32MK1024GPE100  
Set uart2io.uartioenabled true  
Set uart2io.output window    
Hwtool SIM  
Program build/test/out/<b>test_module1.out</b>  
Sleep 200  
Run  
Wait 1000  
Quit  

And there is ruby script file for the test_fixture in project.yml. Same as the example:  
``` 
    :test_fixture:  
        :executable: ruby  
        :name: "Microchip simulator test fixture"  
        :stderr_redirect: :win  
        :arguments:  
            - build/test/simulator/sim_test_fixture.rb  
```  

The file sim_test_fixture.rb look like below:  
>OUT_FILE = "simulator_out.txt"  
File.delete OUT_FILE if File.exists? OUT_FILE   
IO.popen("mdb.bat build/test/simulator/instruction_module1.txt > "+ OUT_FILE)  
sleep 10  
if File.exists? OUT_FILE   
       file_contents = File.read OUT_FILE  
       print file_contents  
end  

To automate the test processing for multiple modules (that is normal case) I believe there are two sulotions:
1. Change content of sim_test_fixture.rb to use different instruction files for every module. 
2. Change content of instruction file for every module. 

But that is only theory, there are lots of thing still open to me.  Is there a build in solution in ceedling? Any document abuout it?

**Comment by mvandervoord** [comment]
What is the symptom/problem that you are seeing? 

I agree that this isn't set up the way I would have done so. I'd prefer to have an artifact of each binary left over when I'm finished so that followup releases can depend on them for dependency tracking instead of rebuilding everything. 

It appears the current situation should work, though. The yaml file specifies that each link will create the required build file, execute it, and store away the results before moving on to the next one. Yes, they're all going through the same filename... but it's rebuilt for each test module, yes?

**Comment by kxtchen** [comment]
First thanks very much for that quickly reply! 
I need to explain it with example more clearly.
assume there are two modules need to test with simulator (here is MDB from Mircochip):  
>module1.c  
module2.c  

I have two test for them:  
>test_module1.c  
test_module2.c

After build I have:  
>test_module1.out  
test_module2.out  

Simulator need to know which .out file to load and run. That is done by setting :test_fixture: in "project.yml". And other two seperated additional files:  
 1. "sim_test_fixture.rb" to load MDB with parameter in command line.  
 2. "instruction_module1.txt" as parameter for the MDB. Inside this file, "test_module1.out" is the only dynamic part.  

The complete procedure is introduced by @JSchaenzle in this topic. I only did some modification according to difference between simulators and MCUs.

My problem is that for module2, test_module2.out is built correctly. But it need to load into simulator after test of module1 is finished. Otherwise, the test_module1.out is loaded and tested again.   
That will need either instruction_module2.txt (another txt file for simulator) or modified "instruction_module1.txt" file ("test_module1.out" replaced with "test_module2.out" ). Anyway I need to change something (file name) at right moment (after test of module1 finished). Without deep knowledge of ceedling, that is not easy task.

**Comment by kxtchen** [comment]
> What is the symptom/problem that you are seeing?
> 
> I agree that this isn't set up the way I would have done so. I'd prefer to have an artifact of each binary left over when I'm finished so that followup releases can depend on them for dependency tracking instead of rebuilding everything.
> 
> It appears the current situation should work, though. The yaml file specifies that each link will create the required build file, execute it, and store away the results before moving on to the next one. Yes, they're all going through the same filename... but it's rebuilt for each test module, yes?

Yes! you are right. I found the solution in the current situation. Only need to add an argument below the test_fixture section:
``` 
   :arguments:  
            - build/test/simulator/sim_test_fixture.rb  
            - ${1}
``` 

Then in the ruby script take the transfered argument (test module  name) to change the instruction file for MDB. I think my question can be close now.
